# Generated by Django 3.1.12 on 2025-05-30 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type_consultation', models.CharField(choices=[('consultation', 'Consultation'), ('contrôle', 'Contrôle')], default='consultation', max_length=20)),
                ('mode', models.CharField(choices=[('présentiel', 'Présentiel'), ('à distance', 'À distance')], default='presentiel', max_length=20)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('terminé', 'Terminé')], default='en attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('lien_visio', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('numero_telephone', models.CharField(default='', max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, default=None, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=10, null=True)),
                ('genre', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_patient', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_patient', to='users.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField()),
                ('lu', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('pieces_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('numero_telephone', models.CharField(default='', max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('debut_carriere', models.DateField(blank=True, default=None, null=True)),
                ('prix_consultation', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('genre', models.CharField(default='', max_length=255)),
                ('date_naissance', models.DateField(blank=True, default=None, null=True)),
                ('titre_professionnel', models.CharField(choices=[('Docteur', 'Docteur'), ('Assistant', 'Assistant'), ('Maître-assistant', 'Maître-assistant'), ('Maître de conférences', 'Maître de conférences'), ('Professeur', 'Professeur'), ('Chef de service', 'Chef de service')], default='Docteur', max_length=255)),
                ('photo', models.TextField(blank=True, null=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissement_medecin', to='users.etablissement')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialite_medecin', to='users.specialite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_medecin', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_medecin', to='users.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10)),
                ('matin_debut', models.TimeField(blank=True, null=True)),
                ('matin_fin', models.TimeField(blank=True, null=True)),
                ('apresmidi_debut', models.TimeField(blank=True, null=True)),
                ('apresmidi_fin', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id_conge', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default='2000-01-01')),
                ('start_period', models.CharField(choices=[('matin', 'Matin'), ('apres-midi', 'Après-midi')], default='matin', max_length=20)),
                ('end_date', models.DateField(default='2000-01-01')),
                ('end_period', models.CharField(choices=[('matin', 'Matin'), ('apres-midi', 'Après-midi')], default='apres-midi', max_length=20)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
