from django.urls import path
from .views import (
    signup_api,
    login_api,
    get_user_by_name,
    get_all_medecins,
    get_medecin_by_email,
    create_medecin,
    update_medecin,
    get_conges_medecin_by_email,
    supprimer_conge,
    modifier_conge,
    ajouter_conge,
    update_patient,
    create_patient,
    get_patient_by_email,
    get_medecin_disponibilite,
    update_medecin_dispo_overwrite_mode,
    test_api,
    get_all_users,
    delete_user, 
    update_user,
    supprimer_etablissement,
    modifier_etablissement,
    ajouter_etablissement,
    liste_etablissements,
    create_rendezvous,
    lister_rendezvous,
    modifier_rendezvous,
    supprimer_rendezvous,
    get_rendezvous_patient,
    annuler_rendezvous,
    get_rendezvous_medecin,
    get_user_nom_prenom,
    envoyer_message, 
    boite_reception,
    liste_villes, 
    ajouter_ville, 
    modifier_ville, 
    supprimer_ville,
    liste_specialites, 
    ajouter_specialite, 
    modifier_specialite, 
    supprimer_specialite,
    rappels_rdv,
    assistant_medical, 
    reset_chat_view,
    noter_experience,
    get_medecin_evaluations
    
)

urlpatterns = [
    # 🔐 Authentification
    path('api/signup/', signup_api, name='signup_api'),
    path('api/login/', login_api, name='login_api'),

    # 👤 Utilisateur
    path('api/users/<str:username>/', get_user_by_name, name='get_user_by_name'),

    # 🩺 Médecin CRUD
    path('api/medecins/', get_all_medecins, name='get_all_medecins'),                    # GET : liste tous
    path('api/medecin/<str:email>/', get_medecin_by_email, name='get_medecin_by_email'), # GET : 1 par email
    path('api/medecin/create/', create_medecin, name='create_medecin'),                  # POST : créer
    path('api/medecin/update/<str:email>/', update_medecin, name='update_medecin'),      # PUT : modifier
    path('api/conges/<str:email>/', get_conges_medecin_by_email), # lister tous les congés du médecin "../api/conges/adresse_medecin@gmail.com/"
    path('api/conge/create/', ajouter_conge),
    path('api/conge/update/<str:id>/', modifier_conge),
    path('api/conge/delete/<str:id>/', supprimer_conge),
    path('api/patient/<str:email>/', get_patient_by_email),
    path('api/patient/create/', create_patient),
    path('api/patient/update/<str:email>/', update_patient),
    path('api/test_api/', test_api),
    path('api/disponibilites/<str:email>/', get_medecin_disponibilite),
    path('api/update/disponibilites/<str:email>/', update_medecin_dispo_overwrite_mode),
    path('api/utilisateurs/', get_all_users),
    path('api/utilisateurs/delete/<int:id>/', delete_user),
    path('api/utilisateurs/update/<int:id>/', update_user),
    path('api/etablissements/', liste_etablissements),
    path('api/etablissements/create/', ajouter_etablissement),
    path('api/etablissements/update/<int:id>/', modifier_etablissement),
    path('api/etablissements/delete/<int:id>/', supprimer_etablissement),
    path('api/rendezvous/create/', create_rendezvous),
    path('api/rendezvous/', lister_rendezvous),
    path('api/rendezvous/delete/<int:id>/', supprimer_rendezvous),
    path('api/rendezvous/update/<int:id>/', modifier_rendezvous),
    path('api/rendezvous/patient/<str:email>/', get_rendezvous_patient),
    path('api/rendezvous/<int:id>/annuler/', annuler_rendezvous),
    path('api/rendezvous/medecin/<str:email>/', get_rendezvous_medecin),
    path('api/user-nom-prenom/<int:user_id_param>/', get_user_nom_prenom),
    # path('api/messages/envoyer/', envoyer_message, name='envoyer_message'),
    # path('api/messages/reception/<str:email>/', boite_reception, name='boite_reception'),
    # path('api/messages/envoyes/<str:email>/', messages_envoyes, name='messages_envoyes'),
    # path('api/messages/lu/<int:id>/', marquer_comme_lu, name='marquer_comme_lu'),    
    path('api/villes/', liste_villes),
    path('api/villes/create/', ajouter_ville),
    path('api/villes/update/<int:id>/', modifier_ville),
    path('api/villes/delete/<int:id>/', supprimer_ville), 
    path('api/specialites/', liste_specialites),
    path('api/specialites/create/', ajouter_specialite),
    path('api/specialites/update/<int:id>/', modifier_specialite),
    path('api/specialites/delete/<int:id>/', supprimer_specialite),
    path('api/messages/send/', envoyer_message, name='envoyer_message'),
    path('api/messages/inbox/<str:email>/', boite_reception),
    path('api/rappels/<str:email>/', rappels_rdv),    
    path('api/medical-chat/', assistant_medical, name='assistant_medical'),
    path('api/chatbot/reset/', reset_chat_view, name='reset_chat'),
    path('api/rendezvous/<int:pk>/noter/', noter_experience, name='noter-experience'),
    path('api/medecin/<int:user_id>/evaluations/', get_medecin_evaluations, name='medecin_evaluations'),

]
